### ISSUE TITLE
How to train my own motionclip model?

### ISSUE THREAD

**Issue by meongeun** [XingliangJin/MCM-LDM#12]
This model uses different architecture from the original MotionCLIP model (https://github.com/GuyTevet/MotionCLIP). 
Layer numbers are different(8 -> 9), skip addition is added, feats are used as motion representation and so on. 
So, I want to train the motionclip version in MCM-LDM code in folder motionclip_263. But I don't have feats as key in the db file. The code in MCM-LDM motionclip_263 amass_parser also doesn't generate "feats" key. How did you make "feats" in df file? Or is there any way to use original motionclip parameters directly to MCM-LDM model? 

MCM-LDM > mld > models > motionclip_263 > datasets > amass.py 
feats = np.split(self.db['feats'][seq_idx][:n_frames_in_use], n_sub_seq)
KeyError: 'feats'

If I fix the code to this which was commented. 
feats = np.split(self.db['joints3d'][seq_idx][:n_frames_in_use], n_sub_seq)
Then gets this error. 
MCM-LDM > mld > models > motionclip_263 > datasets > dataset.py 
ret = ret.permute(1, 2, 0).contiguous()
RuntimeError: number of dims don't match in permute

**Comment by XingliangJin** [comment]
I'm sorry, but we haven't open-sourced the code for retraining MotionClip in this version. However, I can provide some guidelines:

Firstly, we modified the dataset preprocessing part for MotionClip. The original MotionClip uses the Babel dataset (processed from the AMASS dataset) and uses rotation as its data format. Since our MCM-LDM project uses the HumanML3D dataset, which has a data structure of "feats 263" (created using a script provided by HumanML3D that also processes AMASS data), we improved the processing step from AMASS to Babel to obtain the pre-processed pt data in the 263 format. So, if you want to retrain MotionClip model in MCM-LDM, modifying this data processing step is essential. Since the data formats used by MotionCLIP and MCM-LDM are different, the original model of MotionCLIP cannot be used directly.

Next, we adjusted the data load code for MotionClip, along with the network and certain parameters to achieve better reconstruction results. This included adding normalization to the data, using the VAE framework from MLD, and changing the reconstruction loss from MSE loss to L1 loss, among other adjustments.

**Comment by meongeun** [comment]
I’m having some difficulty understanding the data processing method you described for converting the AMASS dataset to the 263 feature format. When I load an AMASS .npz file, the only keys I find are: ['poses', 'gender', 'mocap_framerate', 'betas', 'marker_data', 'dmpls', 'marker_labels', 'trans']. Additionally, in reviewing the HumanML3D code, I couldn't find any lines specific to extracting the 263 features.

Would it be possible for you to share the preprocessing code used to obtain the 263 features, or perhaps direct me to any reference papers or code sources where this process is detailed? I’d be very grateful for any guidance you could provide.

**Comment by XingliangJin** [comment]
You can check these two files in HumanML3D: [raw_pose_processing.ipynb](https://github.com/EricGuo5513/HumanML3D/blob/main/raw_pose_processing.ipynb) and [motion_representation.ipynb](https://github.com/EricGuo5513/HumanML3D/blob/main/motion_representation.ipynb) . And I have upload my [parser code](https://github.com/XingliangJin/MCM-LDM/blob/main/prepare/amass_parser_feat.py) in this project, you can check it.

**Comment by meongeun** [comment]
Thank you so much! :)
