### ISSUE TITLE
Evaluation data

### ISSUE THREAD

**Issue by Boeun-Kim** [XingliangJin/MCM-LDM#9]
Thanks for the great work!

In the paper, for the CRA metric, the authors mentioned that "We train a content classifier as a feature extractor using [49] on a subset of the HumanML3D test set with annotated content labels".
The same process is applied to the SRA with another subset.

Could you specify the "subsets" and how you got content and style labels?

Many thanks.

**Comment by XingliangJin** [comment]
Due to the length of the main manuscript, we have included this information in the [supplementary materials](https://openaccess.thecvf.com/content/CVPR2024/supplemental/Song_Arbitrary_Motion_Style_CVPR_2024_supplemental.zip). In brief, training the style classifier uses a style motion dataset obtained by segmenting several long motions (each one has its own style label) from the CMU dataset, while training the content classifier uses a content motion dataset from a portion of the CMU dataset that has been annotated with content label.

**Comment by Boeun-Kim** [comment]
Thank you Xingliang!

Your study is very impressive and I'd like to cite it in my next paper.
But I'm struggling with evaluation now.
If you don't mind, could you provide the code for SRA?
Or if you can't, could you let me know the source (other repository) where
you referred?

I read the attached supplementary materials, thank you!
I'm a little confused about the datasets in Table 1.
Did you train with full HumanML3D, and evaluate with chosen 30 motions in
CMU datasets?
Or did you train with CMU datasets for the style motion?

Many thanks!
Best wishes,
Boeun Kim

2024년 10월 9일 (수) 오전 11:51, Xingliang Jin ***@***.***>님이 작성:

**Comment by XingliangJin** [comment]
1. You can refer [ACTOR](https://github.com/Mathux/ACTOR) for evaluation SRA (ACTOR compute the accuracy of action label).
2. We train with full HumanML3D, and ecaluate with chosen motions in CMU dataset. Actually, CMU dataset is a subset of HumanML3D.

I guess your expriment is also trained with HumanML3D. I recommand using the evaluation code in [SMooDi](https://github.com/neu-vi/SMooDi), which is done in standard style motion dataset [100STYLE](https://www.ianxmason.com/100style/).

**Comment by XingliangJin** [comment]
We have just initially open-sourced the evaluation code in [here.](https://github.com/XingliangJin/Eval_MCM-LDM) You are welcome to give it a try!
